// test fork

final List<Map<String, dynamic>> latestUpdateManhwa = [
    {
        "id": 1,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/7337cadb-b65a-4210-94cb-0b7ccef75d3c/dForCMaHDHgcfDsQj6MTZZPR2JxmAw8MuEkJBsJM.png",
        "judul": "Quest Supremacy",
        "synopsis": "Kim SooHyun is an ordinary high schooler who isn’t good at studying, fighting, or being attractive. Suddenly, he’s faced with a quest window right in front of his eyes. After being given the powers of a game [system] out of nowhere, how will our hero confront the challenges ahead of him?",
        "content": "https://media.reaperscans.com/file/4SRBHm/comics/7337cadb-b65a-4210-94cb-0b7ccef75d3c/chapters/ffd24c7c-5a14-4685-a21f-a5e1efc98b13/01.jpg",
        "ratingstar": "4.5",
        "ratingaverage": "Average 4.5 / 5 out of 81",
        "rank": "26th in Comics",
        "author": "Hongsil",
        "artist": "Jipery",
        "genre": "Action, Adventure, Comedy, Game",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
        "chapter": "Chapter 1 - Kiss?",
        "imgchapter": "https://media.reaperscans.com/file/4SRBHm/comics/7337cadb-b65a-4210-94cb-0b7ccef75d3c/18030df1-07f1-419c-8edb-bc8872fce410/1tknRzfRFFfwFCsyuJmCyTx9YYyWzIW6EnJrfvdi.jpg"
    },
    {
        "id": 2,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/81bece70-9dcf-4453-80b9-4dae44ece435/dXMFbumgLbWpwyJtj7sLWY5s011WvwwwI7BMMNEp.png",
        "judul": "Barbarian Quest",
        "synopsis": "Sky Mountain Range adalah tempat peristirahatan bagi jiwa-jiwa, dan yang hidup tidak diizinkan untuk melintasinya. Semua orang percaya seperti itu. “Kamu akan menjadi pejuang yang hebat, Urich.” Urich, pejuang suku terkuat, memunggungi rumahnya dan berkelana ke dunia yang beradab.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_625ed1bd59376/af22e3b6828014f0f61c1d1086387c87/01.jpg",
        "ratingstar": "4.9",
        "ratingaverage": "Average 4.9 / 5 out of 14",
        "rank": " 58th in Comics",
        "author": "Yu So Nan",
        "artist": "D&C Webtoon,Uk Jag Ga",
        "genre": "Action, Adventure, Fantasy, Magic",
        "type": "Manhwa",
        "release": "2018",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/04/20050017/01-5.jpg"
    },
    {
        "id": 3,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/11/25052922/KTH.jpg",
        "judul": "Kill The Hero",
        "synopsis": "Setelah dia dibunuh oleh pemimpin guildnya sendiri, Woojin mendapat kesempatan untuk memulai kembali hidupnya. Kali ini dia tidak tertarik untuk menyelamatkan dunia dari monster—dia mengarahkan pandangannya untuk balas dendam! Skill tingkat tingginya dengan cepat membuatnya terkenal di antara player, Tapi ada sesuatu yang tidak diketahui siapa pun: Kepihak mana dia memihak?",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_63705dc368b07/5ba4ae8702972028eb8614599d37a566/01.jpg",
        "ratingstar": "5",
        "ratingaverage": "Average 5 / 5 out of 8",
        "rank": "74th in Comics",
        "author": "D-Dart",
        "artist": "Carrotoon",
        "genre": "Action, Adventure, Fantasy, Psychological, Revenge",
        "type": "Manhwa",
        "release": "2021",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/11/13102540/KTH-114-1.jpg"
    },
    {
        "id": 4,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/08/06190405/Villain-to-Kill-210x300.jpg",
        "judul": "Villain to Kill",
        "synopsis": "Setelah dituduh membunuh seorang rekannya, Akhirnya Kematian Datang pada Cassian Lee Saat dia mengira semuanya sudah berakhir, jiwanya tiba-tiba dirasuki oleh tubuh anak laki-laki dan dia terbangun sebagai Villain",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62fa76ed14513/9746d907bc5efdbd30c3c9d2ee2c34c1/01.jpg",
        "ratingstar": "4.8",
        "ratingaverage": " Average 4.8 / 5 out of 32",
        "rank": " 58th in Comics",
        "author": "D-Dart",
        "artist": "Carrotoon",
        "genre": "Action, Fantasy, Shounen, Violence",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/08/20044523/VTK-64.jpg"
    },
    {
        "id": 5,
        "poster": "https://cdn.novelupdates.com/images/2022/08/Reaper-of-the-Drifting-Moon.jpg",
        "judul": "Reaper of the Drifting Moon",
        "synopsis": "Dia Terjebak di “Sisi Gelap” Dunia Murim nan kelam dan kejam, Sebagai Seorang “Assassin”. Bukalah Matamu yang lebar dan Teruslah Waspada, Jika kau tak ingin Diseret Kedalam Kegelapan Abadi.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62d1979301ccc/f215e9d00b876a0447d2188b05ac909e/01.jpg",
        "ratingstar": "4.6",
        "ratingaverage": "Average 4.6 / 5 out of 118",
        "rank": "6th in Comics",
        "author": "Updating",
        "artist": "Redice Studio",
        "genre": "Action, Adventure, Drama, Martial Arts, Murim, Psychological, Revenge",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/07/20053206/0.webp"
    },
    {
        "id": 6,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/4a8f0911-7427-4190-8afb-224d35ce10f9/iQfrUDq4XdDhB8Tgr7ls4nglnd56xFaA4pkqeiRK.jpg",
        "judul": "Damn Reincarnation",
        "synopsis": "Warrior Hamel bertualang dengan teman-temannya untuk mengalahkan Demon King, Namun setelah mati tepat sebelum pertempuran terakhir dengan Raja Iblis…. “Waaah.” ‘Apa-apaan ini! Dia bereinkarnasi sebagai keturunan dari rekan pejuangnya, Vermouth. Hamel yang sekarang dikenal sebagai Eugene Lionheart terlahir kembali dengan darah The Great Vermouth. Dengan tubuh yang memiliki spesifikasi lebih tinggi sejak awal, ia menunjukkan pertumbuhan eksplosif yang jauh melampaui apa yang telah ia capai dalam kehidupan sebelumnya.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62b32c5641a76/303c8334def3e0ea856bc0369efb40a9/07-copy.jpg",
        "ratingstar": "4.7",
        "ratingaverage": "Average 4.7 / 5 out of 188",
        "rank": "1st in Comics",
        "author": "Mokma",
        "artist": "Copin Comics,Kiki,Park JungYeol",
        "genre": "Action, Adventure, Fantasy, Manhwa",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/06/20050736/028.jpg"
    },
    {
        "id": 7,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/312fc4a4-ce24-46e3-b4e6-38ee08d20c40/eLPLlwDRZPgaw7rxmLuPmyzJ3k0MWeBstWCLNHBV.png",
        "judul": "Nano Machine",
        "synopsis": "Setelah direndahkan dan menghabiskan hidupnya dalam bahaya, seorang yatim piatu dari pemuja iblis, Yeo-Woon, mendapatkan kunjungan tak terduga dari keturunannya dari masa depan yang memasukkan sebuah mesin nano ke dalam tubuh Cheon-Woon, yang mengubah hidup Cheon Yeo Woon setelah aktivasi. Ikuti Cerita tentang perjalanan Cheon Yeo-Woon di reaperscans.id, melewati pemujaan setan dan naik menjadi yang ahli beladiri terbaik baru saja dimulai.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_624151ddb87fd/d8678b7704906e24f84cffadb0c99ca8/01.jpg",
        "ratingstar": "4.7",
        "ratingaverage": "Average 4.7 / 5 out of 214",
        "rank": " 3rd in Comics",
        "author": "Han-Joong-Wueol-Ya",
        "artist": "Guem-Gang-Bul-Gae",
        "genre": "Action, Adventure, Fantasy, Manhwa",
        "type": "Manhwa",
        "release": "2020",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/03/20062830/99.png"
    },
    {
        "id": 8,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/92e822a8-b6e9-40e8-beef-4e9519adfd11/sgjmmD1QTgMdQsSwVrO66n2iIooM1p9jSp0vS1Sf.jpg",
        "judul": "Magic Academy Survival Guide",
        "synopsis": "Setelah direndahkan dan menghabiskan hidupnya dalam bahaya, seorang yatim piatu dari pemuja iblis, Yeo-Woon, mendapatkan kunjungan tak terduga dari keturunannya dari masa depan yang memasukkan sebuah mesin nano ke dalam tubuh Cheon-Woon, yang mengubah hidup Cheon Yeo Woon setelah aktivasi. Ikuti Cerita tentang perjalanan Cheon Yeo-Woon di reaperscans.id, melewati pemujaan setan dan naik menjadi yang ahli beladiri terbaik baru saja dimulai.",
        "content": "https://media.reaperscans.com/file/4SRBHm/comics/92e822a8-b6e9-40e8-beef-4e9519adfd11/chapters/06e04c4e-e840-46a9-9574-94823e6e6bc3/01f.jpg",
        "ratingstar": "5",
        "ratingaverage": "Average 5 / 5 out of 13",
        "rank": "49th in Comics",
        "author": "Kakao",
        "artist": "Kakao",
        "genre": "Action, Adventure, Fantasy, Isekai, Magic, Manhwa",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": ""
    },
    {
        "id": 9,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/b9b38203-4554-4f7a-bac2-dac42450601f/3dBzYlVbNwbeEOD7mDrbjyu6OG285EEbU8MPrD0w.png",
        "judul": "Academys Undercover Professor",
        "synopsis": "Magic exists here, and new progress was rapidly being made in science while magic stagnated in the name of tradition. Using my earthly knowledge and not bound by the traditional thinking, I was able to do things other wizards couldnt even imagine. Still, inadvertently becoming an undercover professor for a mysterious secret society at the renowned Sören academy was never in my to-do list!",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_629b6357e9d2b/57cc502b0cb6837e52dd2ce48f1cef9c/001.jpg",
        "ratingstar": "4.8",
        "ratingaverage": "Average 4.8 / 5 out of 115",
        "rank": "14th in Comics",
        "author": "Sayren",
        "artist": "Sayren",
        "genre": "Action, Adventure, Fantasy, Manhwa, Mystery, School Life, Shounen",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": "https://wuz.reaperscans.id/wp-content/uploads/2022/11/01000930/MASG-1.jpg"
    },
    {
        "id": 10,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/04/06214923/lwg.jpg",
        "judul": "Leveling With God",
        "synopsis": "Cuman dengan menatap mereka saja, manusia biasa bisa kehilangan nyawa mereka. Mereka membuat dunia jatuh dalam kegelapan… setelah puluhan tahun bertarung, survivor terakhir mendapatkan kesimpulan. “Inner takkan bisa mengalahkan Outer” Pada Saat itu, Chronos, Inner Gods yang bisa memanipulasi waktu, mengorbankan dirinya untuk memutar-balikkan waktu. “Jika Begini, kita takkan bisa menang.” “Kembalikan Garis Dunia lama. untuk sekarang” Manusia yang dipilih oleh semua Inner Gods untuk kembali ke masa lalu, manusia terakhir untuk mendaki Tower, orang yang juga dapat bertarung dengan dewa sampai akhir, Kim Yuwon.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62625ed88cb10/241f391d08874567c50b4288214eb451/01.jpg",
        "ratingstar": "4.7",
        "ratingaverage": "Average 4.7 / 5 out of 34",
        "rank": " 57th in Comics",
        "author": "Black Ajin,흑아인",
        "artist": "Ohyeon",
        "genre": "Action, Adventure, Fantasy, Manhwa, Shounen",
        "type": "Manhwa",
        "release": "2021",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": ""
    },
    {
        "id": 11,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/04/25051338/Returner-1-222x300.jpg",
        "judul": "A Returners Magic Should be Special",
        "synopsis": "Selama 10 tahun, Desir dan kelompoknya telah berjuang di dalam Shadow Labyrinth yang misterius—dan melawan akhir dunia. Sebagian besar umat manusia telah binasa dan tepat ketika Desir akan dibunuh, dia dikirim kembali 13 tahun ke masa lalu. Meskipun mengetahui masa depan terkutuk yang ada di depan, Desir menguatkan tekadnya saat dia melihat peluang untuk melatih teman-temannya dan lebih mempersiapkan diri untuk menghadapi Armagedon bersama, tanpa kehilangan orang yang mereka cintai!",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_625ed1bd59376/af22e3b6828014f0f61c1d1086387c87/01.jpg",
        "ratingstar": "4.9",
        "ratingaverage": "Average 4.9 / 5 out of 14",
        "rank": " 58th in Comics",
        "author": "Yu So Nan",
        "artist": "D&C Webtoon,Uk Jag Ga",
        "genre": "Action, Adventure, Fantasy, Magic",
        "type": "Manhwa",
        "release": "2018",
        "status": "OnGoing",
        "chapter": "Chapter 1",
        "imgchapter": ""
    },
];

final List<Map<String, dynamic>> popularManhwa = [
    {
        "id": 1,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/7337cadb-b65a-4210-94cb-0b7ccef75d3c/dForCMaHDHgcfDsQj6MTZZPR2JxmAw8MuEkJBsJM.png",
        "judul": "Quest Supremacy",
        "synopsis": "Kim SooHyun is an ordinary high schooler who isn’t good at studying, fighting, or being attractive. Suddenly, he’s faced with a quest window right in front of his eyes. After being given the powers of a game [system] out of nowhere, how will our hero confront the challenges ahead of him?",
        "content": "https://media.reaperscans.com/file/4SRBHm/comics/7337cadb-b65a-4210-94cb-0b7ccef75d3c/chapters/ffd24c7c-5a14-4685-a21f-a5e1efc98b13/01.jpg",
        "ratingstar": "4.5",
        "ratingaverage": "Average 4.5 / 5 out of 81",
        "rank": "26th in Comics",
        "author": "Hongsil",
        "artist": "Jipery",
        "genre": "Action, Adventure, Comedy, Game",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
    },
    {
        "id": 2,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/81bece70-9dcf-4453-80b9-4dae44ece435/dXMFbumgLbWpwyJtj7sLWY5s011WvwwwI7BMMNEp.png",
        "judul": "Barbarian Quest",
        "synopsis": "Sky Mountain Range adalah tempat peristirahatan bagi jiwa-jiwa, dan yang hidup tidak diizinkan untuk melintasinya. Semua orang percaya seperti itu. “Kamu akan menjadi pejuang yang hebat, Urich.” Urich, pejuang suku terkuat, memunggungi rumahnya dan berkelana ke dunia yang beradab.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_625ed1bd59376/af22e3b6828014f0f61c1d1086387c87/01.jpg",
        "ratingstar": "4.9",
        "ratingaverage": "Average 4.9 / 5 out of 14",
        "rank": " 58th in Comics",
        "author": "Yu So Nan",
        "artist": "D&C Webtoon,Uk Jag Ga",
        "genre": "Action, Adventure, Fantasy, Magic",
        "type": "Manhwa",
        "release": "2018",
        "status": "OnGoing",
    },
    {
        "id": 3,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/11/25052922/KTH.jpg",
        "judul": "Kill The Hero",
        "synopsis": "",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_63705dc368b07/5ba4ae8702972028eb8614599d37a566/01.jpg",
        "ratingstar": "5",
        "ratingaverage": "Average 5 / 5 out of 8",
        "rank": "74th in Comics",
        "author": "D-Dart",
        "artist": "Carrotoon",
        "genre": "Action, Adventure, Fantasy, Psychological, Revenge",
        "type": "Manhwa",
        "release": "2021",
        "status": "OnGoing",
    },
    {
        "id": 4,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/08/06190405/Villain-to-Kill-210x300.jpg",
        "judul": "Villain to Kill",
        "synopsis": "Setelah dituduh membunuh seorang rekannya, Akhirnya Kematian Datang pada Cassian Lee Saat dia mengira semuanya sudah berakhir, jiwanya tiba-tiba dirasuki oleh tubuh anak laki-laki dan dia terbangun sebagai Villain",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62fa76ed14513/9746d907bc5efdbd30c3c9d2ee2c34c1/01.jpg",
        "ratingstar": "4.8",
        "ratingaverage": " Average 4.8 / 5 out of 32",
        "rank": " 58th in Comics",
        "author": "D-Dart",
        "artist": "Carrotoon",
        "genre": "Action, Fantasy, Shounen, Violence",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
    },
    {
        "id": 5,
        "poster": "https://cdn.novelupdates.com/images/2022/08/Reaper-of-the-Drifting-Moon.jpg",
        "judul": "Reaper of the Drifting Moon",
        "synopsis": "Dia Terjebak di “Sisi Gelap” Dunia Murim nan kelam dan kejam, Sebagai Seorang “Assassin”. Bukalah Matamu yang lebar dan Teruslah Waspada, Jika kau tak ingin Diseret Kedalam Kegelapan Abadi.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62d1979301ccc/f215e9d00b876a0447d2188b05ac909e/01.jpg",
        "ratingstar": "4.6",
        "ratingaverage": "Average 4.6 / 5 out of 118",
        "rank": "6th in Comics",
        "author": "Updating",
        "artist": "Redice Studio",
        "genre": "Action, Adventure, Drama, Martial Arts, Murim, Psychological, Revenge",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
    },
    {
        "id": 6,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/4a8f0911-7427-4190-8afb-224d35ce10f9/iQfrUDq4XdDhB8Tgr7ls4nglnd56xFaA4pkqeiRK.jpg",
        "judul": "Damn Reincarnation",
        "synopsis": "Warrior Hamel bertualang dengan teman-temannya untuk mengalahkan Demon King, Namun setelah mati tepat sebelum pertempuran terakhir dengan Raja Iblis…. “Waaah.” ‘Apa-apaan ini! Dia bereinkarnasi sebagai keturunan dari rekan pejuangnya, Vermouth. Hamel yang sekarang dikenal sebagai Eugene Lionheart terlahir kembali dengan darah The Great Vermouth. Dengan tubuh yang memiliki spesifikasi lebih tinggi sejak awal, ia menunjukkan pertumbuhan eksplosif yang jauh melampaui apa yang telah ia capai dalam kehidupan sebelumnya.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62b32c5641a76/303c8334def3e0ea856bc0369efb40a9/07-copy.jpg",
        "ratingstar": "4.7",
        "ratingaverage": "Average 4.7 / 5 out of 188",
        "rank": "1st in Comics",
        "author": "Mokma",
        "artist": "Copin Comics,Kiki,Park JungYeol",
        "genre": "Action, Adventure, Fantasy, Manhwa",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
    },
    {
        "id": 7,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/312fc4a4-ce24-46e3-b4e6-38ee08d20c40/eLPLlwDRZPgaw7rxmLuPmyzJ3k0MWeBstWCLNHBV.png",
        "judul": "Nano Machine",
        "synopsis": "Setelah direndahkan dan menghabiskan hidupnya dalam bahaya, seorang yatim piatu dari pemuja iblis, Yeo-Woon, mendapatkan kunjungan tak terduga dari keturunannya dari masa depan yang memasukkan sebuah mesin nano ke dalam tubuh Cheon-Woon, yang mengubah hidup Cheon Yeo Woon setelah aktivasi. Ikuti Cerita tentang perjalanan Cheon Yeo-Woon di reaperscans.id, melewati pemujaan setan dan naik menjadi yang ahli beladiri terbaik baru saja dimulai.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_624151ddb87fd/d8678b7704906e24f84cffadb0c99ca8/01.jpg",
        "ratingstar": "4.7",
        "ratingaverage": "Average 4.7 / 5 out of 214",
        "rank": " 3rd in Comics",
        "author": "Han-Joong-Wueol-Ya",
        "artist": "Guem-Gang-Bul-Gae",
        "genre": "Action, Adventure, Fantasy, Manhwa",
        "type": "Manhwa",
        "release": "2020",
        "status": "OnGoing",
    },
    {
        "id": 8,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/92e822a8-b6e9-40e8-beef-4e9519adfd11/sgjmmD1QTgMdQsSwVrO66n2iIooM1p9jSp0vS1Sf.jpg",
        "judul": "Magic Academy Survival Guide",
        "synopsis": "Setelah direndahkan dan menghabiskan hidupnya dalam bahaya, seorang yatim piatu dari pemuja iblis, Yeo-Woon, mendapatkan kunjungan tak terduga dari keturunannya dari masa depan yang memasukkan sebuah mesin nano ke dalam tubuh Cheon-Woon, yang mengubah hidup Cheon Yeo Woon setelah aktivasi. Ikuti Cerita tentang perjalanan Cheon Yeo-Woon di reaperscans.id, melewati pemujaan setan dan naik menjadi yang ahli beladiri terbaik baru saja dimulai.",
        "content": "https://media.reaperscans.com/file/4SRBHm/comics/92e822a8-b6e9-40e8-beef-4e9519adfd11/chapters/06e04c4e-e840-46a9-9574-94823e6e6bc3/01f.jpg",
        "ratingstar": "5",
        "ratingaverage": "Average 5 / 5 out of 13",
        "rank": "49th in Comics",
        "author": "Kakao",
        "artist": "Kakao",
        "genre": "Action, Adventure, Fantasy, Isekai, Magic, Manhwa",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
    },
    {
        "id": 9,
        "poster": "https://media.reaperscans.com/file/4SRBHm/comics/b9b38203-4554-4f7a-bac2-dac42450601f/3dBzYlVbNwbeEOD7mDrbjyu6OG285EEbU8MPrD0w.png",
        "judul": "Academys Undercover Professor",
        "synopsis": "Magic exists here, and new progress was rapidly being made in science while magic stagnated in the name of tradition. Using my earthly knowledge and not bound by the traditional thinking, I was able to do things other wizards couldnt even imagine. Still, inadvertently becoming an undercover professor for a mysterious secret society at the renowned Sören academy was never in my to-do list!",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_629b6357e9d2b/57cc502b0cb6837e52dd2ce48f1cef9c/001.jpg",
        "ratingstar": "4.8",
        "ratingaverage": "Average 4.8 / 5 out of 115",
        "rank": "14th in Comics",
        "author": "Sayren",
        "artist": "Sayren",
        "genre": "Action, Adventure, Fantasy, Manhwa, Mystery, School Life, Shounen",
        "type": "Manhwa",
        "release": "2022",
        "status": "OnGoing",
    },
    {
        "id": 10,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/04/06214923/lwg.jpg",
        "judul": "Leveling With God",
        "synopsis": "Cuman dengan menatap mereka saja, manusia biasa bisa kehilangan nyawa mereka. Mereka membuat dunia jatuh dalam kegelapan… setelah puluhan tahun bertarung, survivor terakhir mendapatkan kesimpulan. “Inner takkan bisa mengalahkan Outer” Pada Saat itu, Chronos, Inner Gods yang bisa memanipulasi waktu, mengorbankan dirinya untuk memutar-balikkan waktu. “Jika Begini, kita takkan bisa menang.” “Kembalikan Garis Dunia lama. untuk sekarang” Manusia yang dipilih oleh semua Inner Gods untuk kembali ke masa lalu, manusia terakhir untuk mendaki Tower, orang yang juga dapat bertarung dengan dewa sampai akhir, Kim Yuwon.",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_62625ed88cb10/241f391d08874567c50b4288214eb451/01.jpg",
        "ratingstar": "4.7",
        "ratingaverage": "Average 4.7 / 5 out of 34",
        "rank": " 57th in Comics",
        "author": "Black Ajin,흑아인",
        "artist": "Ohyeon",
        "genre": "Action, Adventure, Fantasy, Manhwa, Shounen",
        "type": "Manhwa",
        "release": "2021",
        "status": "OnGoing",
    },
    {
        "id": 11,
        "poster": "https://wuz.reaperscans.id/wp-content/uploads/2022/04/25051338/Returner-1-222x300.jpg",
        "judul": "A Returners Magic Should be Special",
        "synopsis": "Selama 10 tahun, Desir dan kelompoknya telah berjuang di dalam Shadow Labyrinth yang misterius—dan melawan akhir dunia. Sebagian besar umat manusia telah binasa dan tepat ketika Desir akan dibunuh, dia dikirim kembali 13 tahun ke masa lalu. Meskipun mengetahui masa depan terkutuk yang ada di depan, Desir menguatkan tekadnya saat dia melihat peluang untuk melatih teman-temannya dan lebih mempersiapkan diri untuk menghadapi Armagedon bersama, tanpa kehilangan orang yang mereka cintai!",
        "content": "https://reaperscans.id/wp-content/uploads/WP-manga/data/manga_625ed1bd59376/af22e3b6828014f0f61c1d1086387c87/01.jpg",
        "ratingstar": "4.9",
        "ratingaverage": "Average 4.9 / 5 out of 14",
        "rank": " 58th in Comics",
        "author": "Yu So Nan",
        "artist": "D&C Webtoon,Uk Jag Ga",
        "genre": "Action, Adventure, Fantasy, Magic",
        "type": "Manhwa",
        "release": "2018",
        "status": "OnGoing",
    },
];